version = 1

exclude_patterns = [
  "git-hooks/*",
  "vwo/helpers/enums.py"
]

test_patterns = [
  "tests/**"
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "2.x.x"

  [analyzers.meta]
  max_line_length = 80
  skip_doc_coverage = ["module", "magic", "class"]
