language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
script: "coverage run --source=vwo setup.py test"
after_success:
  - coveralls
